import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import { Suspense } from 'react';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Job Application Tracker',
	description: 'Generated by create next app',
};

function NavbarSkeleton() {
	return (
		<nav className='border-b border-gray-200 bg-white'>
			<div className='container mx-auto flex h-16 items-center px-4 justify-between'>
				<div className='flex items-center gap-2 text-xl font-semibold text-primary'>
					<div className='h-6 w-6 bg-gray-200 animate-pulse rounded' />
					<span>Job Tracker</span>
				</div>
				<div className='h-10 w-24 bg-gray-200 animate-pulse rounded' />
			</div>
		</nav>
	);
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Suspense fallback={<NavbarSkeleton />}>
					<Navbar />
				</Suspense>
				<Toaster position='bottom-right' />
				{children}
			</body>
		</html>
	);
}
